version: '3'
services:
  prometheus:
    image: "prom/prometheus"
    network_mode: "host"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
  grafana:
    image: "grafana/grafana:8.4.1"
    network_mode: "host"
    volumes:
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    container_name: grafana
