global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  - job_name: 'prometheus-grafana-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
    # To be able to scrape an application running on localhost from the container on running Mac (VM)
    # - targets: ['host.docker.internal:8080']
      - targets: ['localhost:8080']
