{
 "title": "Container Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=~\".*\"}, namespace)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=\"$namespace\"}, container)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"$container\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Throttled Periods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(container_cpu_cfs_throttled_periods_total{pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "CPU Throttled Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{pod=~\"$pod\"}[$__rate_interval]))by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Container Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$pod\"}[$__rate_interval]))by(pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{resource=\"cpu\",container=\"$container\",namespace=\"$namespace\"})",
     "legendFormat": "$container container CPU requests"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{resource=\"cpu\",container=\"$container\",namespace=\"$namespace\"})",
     "legendFormat": "$container container CPU limits"
    }
   ]
  },
  {
   "title": "Memory Container Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 7 },
   "repeat": "pod",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - rss"
    },
    {
     "expr": "container_memory_working_set_bytes{pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - wss"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - limit"
    },
    {
     "expr": "container_memory_cache{pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - cache"
    },
    {
     "expr": "container_memory_usage_bytes{pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - usage"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "repeat": "pod",
   "yaxes": [
    { "format": "pps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "(rate(container_network_receive_packets_total{pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-receive"
    },
    {
     "expr": "(rate(container_network_transmit_packets_total{pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-transmit"
    },
    {
     "expr": "(rate(container_network_receive_bytes_total{pod=\"$pod\"}[$__rate_interval])) * 8",
     "legendFormat": "{{pod}}-receive bytes"
    },
    {
     "expr": "(rate(container_network_transmit_bytes_total{pod=\"$pod\"}[$__rate_interval])) * 8",
     "legendFormat": "{{pod}}-transmit bytes"
    }
   ]
  },
  {
   "title": "container network dropped/errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "pps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "(rate(container_network_receive_packets_dropped_total{pod!~\"|sync.*|prometheus.*|ovs.*|sdn.*|ipf.*\",namespace=\"$namespace\",interface=~\"eth.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-dropped-receive ({{interface}})"
    },
    {
     "expr": "(rate(container_network_transmit_packets_dropped_total{pod!~\"|sync.*|prometheus.*|ovs.*|sdn.*|ipf.*\",namespace=\"$namespace\",interface=~\"eth.*\"}[1m]))",
     "legendFormat": "{{pod}}-dropped-transmit ({{interface}})"
    },
    {
     "expr": "(irate(container_network_receive_errors_total{pod!~\"|sync.*|prometheus.*|ovs.*|sdn.*|ipf.*\",namespace=\"$namespace\",interface=~\"eth.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-errors-receive ({{interface}})"
    },
    {
     "expr": "(rate(container_network_transmit_errors_total{pod!~\"|sync.*|prometheus.*|ovs.*|sdn.*|ipf.*\",namespace=\"$namespace\",interface=~\"eth.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}-errors-transmit ({{interface}})"
    }
   ]
  },
  {
   "title": "memory allocation totals",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\"})",
     "legendFormat": "$container memory allocated"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",namespace=~\"$namespace\",container=\"$container\"})",
     "legendFormat": "$container max memory allocation"
    }
   ]
  }
 ]
}