{
 "title": "JVM Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\"})",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Total Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"nonheap\"})",
     "legendFormat": "Commited"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"nonheap\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Serial GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eden Space (SerialGC)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{id=\"Eden Space\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{id=\"Eden Space\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{id=\"Eden Space\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Survivor Space (SerialGC)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{id=\"Survivor Space\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{id=\"Survivor Space\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{id=\"Survivor Space\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Old Generation (SerialGC)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "repeat": "memory_pool_nonheap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{id=\"Tenured Gen\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{id=\"Tenured Gen\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{id=\"Tenured Gen\"}",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Parallel GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eden Space (ParallelGC)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{id=\"PS Eden Space\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{id=\"PS Eden Space\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{id=\"PS Eden Space\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Survivor Space (ParallelGC)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{id=\"PS Survivor Space\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{id=\"PS Survivor Space\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{id=\"PS Survivor Space\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Old Generation (ParallelGC)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{id=\"PS Old Gen\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{id=\"PS Old Gen\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{id=\"PS Old Gen\"}",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "G1 GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Eden Space (G1GC)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "repeat": "memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{id=\"G1 Eden Space\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{id=\"G1 Eden Space\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{id=\"G1 Eden Space\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Survivor Space (G1GC)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{id=\"G1 Survivor Space\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{id=\"G1 Survivor Space\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{id=\"G1 Survivor Space\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Old Generation (G1GC)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{id=\"G1 Old Gen\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{id=\"G1 Old Gen\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{id=\"G1 Old Gen\"}",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Metaspace (Non-Heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"Metaspace\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{id=\"Metaspace\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"Metaspace\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Code Cache  (Non-Heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"Code Cache\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_used_bytes{id=\"CodeHeap 'non-profiled nmethods'\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_committed_bytes{id=\"Code Cache\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_committed_bytes{id=\"CodeHeap 'non-profiled nmethods'\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"Code Cache\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"CodeHeap 'non-profiled nmethods'\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Compressed Class Space  (Non-Heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"Compressed Class Space\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{id=\"Compressed Class Space\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"Compressed Class Space\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Memory Allocation/Promotion Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{}[$__rate_interval])",
     "legendFormat": "Allocated"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{}[$__rate_interval])",
     "legendFormat": "Promoted"
    }
   ]
  },
  {
   "title": "Minor / Major GC Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_pause_seconds_count{action=\"end of major GC\"}[$__rate_interval])",
     "legendFormat": "Major GC - {{cause}}"
    },
    {
     "expr": "increase(jvm_gc_pause_seconds_count{action=\"end of minor GC\"}[$__rate_interval])",
     "legendFormat": "Minor GC - {{cause}}"
    }
   ]
  },
  {
   "title": "Average GC Pause Time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{}[$__rate_interval])/rate(jvm_gc_pause_seconds_count{}[$__rate_interval])",
     "legendFormat": "AVG {{action}} ({{cause}})"
    },
    { "expr": "jvm_gc_pause_seconds_max{}", "legendFormat": "MAX {{action}} ({{cause}})" }
   ]
  },
  {
   "title": "Threads (Deamon/Live)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jvm_threads_daemon_threads{}", "legendFormat": "Daemon" },
    { "expr": "jvm_threads_live_threads{}", "legendFormat": "Live" }
   ]
  },
  {
   "title": "Threads States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{state=\"runnable\"}",
     "legendFormat": "Runnable"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"blocked\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"waiting\"}",
     "legendFormat": "Waiting"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"timed-waiting\"}",
     "legendFormat": "Timed-Waiting"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"new\"}",
     "legendFormat": "New"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"terminated\"}",
     "legendFormat": "Terminated"
    }
   ]
  },
  {
   "title": "Direct Buffers (Non-Heap)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{id=\"direct\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{id=\"direct\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Direct Mapped Buffers (Non-Heap)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{id=\"mapped\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{id=\"mapped\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  }
 ]
}